### ISSUE TITLE
No Typescript types

### ISSUE THREAD

**Issue by dgreene1** [lissitz/react-accessible-treeview#23]
Hi @lissitz. I noticed that there are no typescript types for this library in DefinitelyTyped and the library itself does not export any type information.

I'm one of those people who loves converting JS libraries to TypeScript.

Would you be interested in either:
1. A PR that provides types from within the library but keeps the library?
2. Or, a PR that converts the library to Typescript?

Option 2 is significantly easier for me and is more accurate from consumers since it doesn't allow the type definitions to drift away from the runtime types since they would be derived from the same source.

**Comment by lissitz** [comment]
Hi @dgreene1, feel free to open a PR that rewrites the library in Typescript. I'm open to PRs for fixes/improvements, although I'm not currently interested in further development of the library on my own time.

**Comment by dgreene1** [comment]
Thank you for the info @lissitz. Just in case our company (who is doing major accessibility work) agrees to allocating people’s time, I want to check to see if you’d be willing to accept me being added as a maintainer so I can assist/control the publishing/releases so that a11y and security patches can be released in a timely manner?

You could keep the library in your namespace/org since that’s a pain. This would be just an offer to have a 2nd maintainer who _might_ have budget during work hours (still waiting to hear back from our engineering budget people at the company).

**Comment by lissitz** [comment]
Yes, I'm open to eventually adding you as a maintainer 🙂.
